# Generated by Django 3.1 on 2020-08-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0002_criminal_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='crime',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
