# Generated by Django 3.1 on 2020-08-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0003_criminal_crime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='pic',
        ),
        migrations.AddField(
            model_name='criminal',
            name='criminal_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criminal',
            name='photo',
            field=models.ImageField(blank=True, default='criminals/missing.jpeg', upload_to='criminals/'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='phys_desc',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='criminal',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='location',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
