# Generated by Django 3.1 on 2020-08-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0006_auto_20200831_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='state_id',
            new_name='state',
        ),
    ]
