# Generated by Django 3.1 on 2020-08-31 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0007_auto_20200831_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='location',
        ),
        migrations.AddField(
            model_name='criminal',
            name='city',
            field=models.ForeignKey(default=709, on_delete=django.db.models.deletion.CASCADE, to='criminals.cities'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='state',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='criminals.states'),
        ),
    ]
