# Generated by Django 3.1 on 2020-09-02 04:50

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0008_auto_20200831_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='criminals.cities'),
        ),
    ]
