# Generated by Django 3.1 on 2020-09-02 06:19

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200902_0518'),
        ('criminals', '0009_auto_20200902_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='upload.cities'),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='state',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='upload.states'),
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='States',
        ),
    ]
