# Generated by Django 3.1 on 2020-09-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0010_auto_20200902_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='phys_desc',
        ),
        migrations.AddField(
            model_name='criminal',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criminal',
            name='arresting_agency',
            field=models.CharField(default='pj', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criminal',
            name='crime_type',
            field=models.CharField(default='theft', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criminal',
            name='date',
            field=models.DateField(default='2005-02-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criminal',
            name='physical_description',
            field=models.TextField(blank=True),
        ),
    ]
