# Generated by Django 3.1 on 2020-09-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200902_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcriminal',
            name='photo',
            field=models.ImageField(upload_to='criminals/'),
        ),
    ]
